### ISSUE TITLE
Client-Side Crash with Supply Carts [Description: Rendering entity in world]

### ISSUE THREAD

**Issue by SalkNL** [jmb05/nifty-carts#20]
I verified this crash twice now, once in multiplayer on a LAN server and the second time playing on a singleplayer map. 

It happens when taking items in and out from the supply cart or moving them around. I'm assuming this is happening because the cart is trying to render the items inside to show them on the cart and it breaks the game. 

Here's part of the crash log: 

-- Entity being rendered --
Details:
	Entity Type: niftycarts:supply_cart (net.jmb19905.niftycarts.entity.SupplyCartEntity)
	Entity ID: 1943
	Entity Name: Supply Cart
	Entity's Exact location: 323.00, 120.00, 550.80
	Entity's Block location: World: (322,120,550), Section: (at 2,8,6 in 20,7,34; chunk contains blocks 320,-64,544 to 335,319,559), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,-64,512 to 511,319,1023)
	Entity's Momentum: 0.00, -0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
	Entity NBT: {Air:300s,BalmData:{},FallDistance:0.0f,Fire:-1s,Invulnerable:0b,Items:[],Motion:[0.0d,0.0d,0.0d],OnGround:1b,PortalCooldown:0,Pos:[322.9988888949959d,120.0d,550.8007146550849d],Rotation:[-144.84375f,25.0f],UUID:[I;-1236051087,821447953,-1450433358,-1805873822],cardinal_components:{"realisticfirespread:allow_fire_spread":{AllowFireSpread:0b}},cpaCooldown:0,cpadidTP:0b}
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:145)
	at net.minecraft.class_761.method_22977(class_761.java:1574)
	at net.minecraft.class_761.invokeRenderEntity(class_761.java)
	at net.irisshaders.iris.shadows.ShadowRenderer.renderEntities(ShadowRenderer.java:637)
	at net.irisshaders.iris.shadows.ShadowRenderer.renderShadows(ShadowRenderer.java:507)
	at net.irisshaders.iris.pipeline.IrisRenderingPipeline.renderShadows(IrisRenderingPipeline.java:1009)
	at net.minecraft.class_761.handler$gfe000$iris$renderTerrainShadows(class_761.java:15550)
	at net.minecraft.class_761.method_22710(class_761.java:1241)
	at net.minecraft.class_757.method_3188(class_757.java:1110)
	at net.minecraft.class_757.method_3192(class_757.java:880)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:551)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:84)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)

-- Renderer details --
Details:
	Assigned renderer: net.jmb19905.niftycarts.client.renderer.entity.SupplyCartRenderer@7a0605a4
	Location: 0.94,-1.62,2.13 - World: (0,-2,2), Section: (at 0,14,2 in 0,-1,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Rotation: -144.84375
	Delta: 0.579231
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:145)
	at net.minecraft.class_761.method_22977(class_761.java:1574)
	at net.minecraft.class_761.invokeRenderEntity(class_761.java)
	at net.irisshaders.iris.shadows.ShadowRenderer.renderEntities(ShadowRenderer.java:637)
	at net.irisshaders.iris.shadows.ShadowRenderer.renderShadows(ShadowRenderer.java:507)
	at net.irisshaders.iris.pipeline.IrisRenderingPipeline.renderShadows(IrisRenderingPipeline.java:1009)
	at net.minecraft.class_761.handler$gfe000$iris$renderTerrainShadows(class_761.java:15550)
	at net.minecraft.class_761.method_22710(class_761.java:1241)
	at net.minecraft.class_757.method_3188(class_757.java:1110)
	at net.minecraft.class_757.method_3192(class_757.java:880)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:551)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:84)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)

**Comment by jmb05** [comment]
On first glance this seems to be an incompatibility with Iris. Unfortunately I do not have the time to look at this issue at the moment so fixing it will take a while.

**Comment by SalkNL** [comment]
Is there any way to disable the visual part of the mod? just keeping the plain carts around for the supply cart only? 

I checked the .Jar hope that's ok. I saw that SupplyCartRenderer$ContentsRenderer.class and SupplyCartRenderer$Contents.class are the files that take care of rendering the inventory items in the world. Tried editing to False on Eclipse but my knowledge of java is limited and i didn't know how to compile it correctly lol

**Comment by jmb05** [comment]
There is currently no way to disable the visual parts of the mod but I will add config options for that in the future.

**Comment by jmb05** [comment]
Upon further inspection this seems to be an incompatibility with the Quilt Loader. I do not use Quilt and don't test the mod against it. Which means if no one else contributes a fix, this issue will unfortunately persist. But I will add the configuration options which should hopefully serve as a workaround.
