### ISSUE TITLE
Incompatibility with pathunderfencegates / crash when using plow with shovels

### ISSUE THREAD

**Issue by dhannyjsb** [jmb05/nifty-carts#26]
crash when use Plow with shovels 

>[15:17:32] [Server thread/INFO]: dhannyjsb[/127.0.0.1:61362] logged in with entity id 19 at (36.70613804073826, 64.0, -544.8949580618231)
[15:17:32] [Server thread/INFO]: multiplayer.player.joined
[15:17:33] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchFieldError: Class net.minecraft.class_5712 does not have member field 'net.minecraft.class_5712 field_28733'
        at net.minecraft.class_1821.handler$cbd000$pathunderfencegates$useOnBlockInject(class_1821.java:1067) ~[server-intermediary.jar:?]
        at net.minecraft.class_1821.method_7884(class_1821.java:41) ~[server-intermediary.jar:?]
        at net.jmb19905.niftycarts.entity.PlowEntity.plow(PlowEntity.java:87) ~[niftycarts-3.4.1+1.20.6.jar:?]
        at net.jmb19905.niftycarts.entity.PlowEntity.pulledTick(PlowEntity.java:70) ~[niftycarts-3.4.1+1.20.6.jar:?]
        at net.jmb19905.niftycarts.util.NiftyWorld.tick(NiftyWorld.java:61) ~[niftycarts-3.4.1+1.20.6.jar:?]
        at net.jmb19905.niftycarts.NiftyCarts.lambda$onInitialize$10(NiftyCarts.java:155) ~[niftycarts-3.4.1+1.20.6.jar:?]
        at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$2(ServerTickEvents.java:43) ~[fabric-lifecycle-events-v1-2.3.4+c5fc38b3b0-ffaf3a09b85cb754.jar:?]
        at net.minecraft.server.MinecraftServer.handler$zpp000$fabric-lifecycle-events-v1$onEndTick(MinecraftServer.java:3098) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:917) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:691) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:275) ~[server-intermediary.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1570) [?:?]
[15:17:33] [Server thread/ERROR]: This crash report has been saved to: D:\Project_MC_Moded_Server\server\Thebegin\.\crash-reports\crash-2024-05-11_15.17.33-server.txt
[15:17:33] [Server thread/INFO]: Starting shutdown process...
[15:17:33] [Server thread/INFO]: Closing storage...
[15:17:33] [Server thread/INFO]: Goodbye!
[15:17:33] [Server thread/INFO]: Stopping server
[15:17:33] [Server thread/INFO]: Saving players
[15:17:33] [Server thread/INFO]: Saving worlds
[15:17:35] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[15:17:35] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_end
[15:17:35] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_nether
[15:17:35] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/nmr:astral_plane
[15:17:35] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[15:17:35] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[15:17:35] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[15:17:35] [Server thread/INFO]: ThreadedAnvilChunkStorage (astral_plane): All chunks are saved
[15:17:35] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved

Mod list 

> [15:17:08] [main/INFO]: Loading 126 mods:
        - adorabuild_structures 2.6.1
        - antixray 1.3.3
           \-- com_moandjiezana_toml_toml4j 0.7.2
        - appleskin 3.0.0+mc1.20.5
        - areas 5.8
        - backslot 1.2.15
           \-- amecsapi 1.5.5+mc1.20.2
        - backslotaddon 1.1.1
        - beautifiedchatserver 2.4
        - beautify 1.2.0+1.20.6
        - betterimpaling 2.0.8
        - biomesoplenty 18.4.0.3
        - birds-boids 1.1.0
        - boids 1.1.1
        - c2me 0.2.0+alpha.11.95+1.20.6
           |-- c2me-base 0.2.0+alpha.11.95+1.20.6
           |-- c2me-client-uncapvd 0.2.0+alpha.11.95+1.20.6
           |-- c2me-fixes-chunkio-threading-issues 0.2.0+alpha.11.95+1.20.6
           |-- c2me-fixes-general-threading-issues 0.2.0+alpha.11.95+1.20.6
           |-- c2me-fixes-worldgen-threading-issues 0.2.0+alpha.11.95+1.20.6
           |-- c2me-fixes-worldgen-vanilla-bugs 0.2.0+alpha.11.95+1.20.6
           |-- c2me-notickvd 0.2.0+alpha.11.95+1.20.6
           |-- c2me-opts-allocs 0.2.0+alpha.11.95+1.20.6
           |-- c2me-opts-chunk-access 0.2.0+alpha.11.95+1.20.6
           |-- c2me-opts-chunkio 0.2.0+alpha.11.95+1.20.6
           |-- c2me-opts-math 0.2.0+alpha.11.95+1.20.6
           |-- c2me-opts-scheduling 0.2.0+alpha.11.95+1.20.6
           |-- c2me-opts-worldgen-general 0.2.0+alpha.11.95+1.20.6
           |-- c2me-opts-worldgen-vanilla 0.2.0+alpha.11.95+1.20.6
           |-- c2me-rewrites-chunk-serializer 0.2.0+alpha.11.95+1.20.6
           |-- c2me-rewrites-chunkio 0.2.0+alpha.11.95+1.20.6
           |-- c2me-server-utils 0.2.0+alpha.11.95+1.20.6
           |-- c2me-threading-chunkio 0.2.0+alpha.11.95+1.20.6
           |-- c2me-threading-lighting 0.2.0+alpha.11.95+1.20.6
           |-- c2me-threading-worldgen 0.2.0+alpha.11.95+1.20.6
           |-- com_ibm_async_asyncutil 0.1.0
           |-- net_objecthunter_exp4j 0.4.8
           \-- org_threadly_threadly 7.0
        - cloth-config 14.0.126
           \-- cloth-basic-math 0.6.1
        - collective 7.57
        - debugify 1.20.6+1.0
        - doubledoors 5.6
        - entityculling 1.6.4
        - fabric-api 0.98.0+1.20.6
           |-- fabric-api-base 0.4.40+80f8cf51b0
           |-- fabric-api-lookup-api-v1 1.6.59+e9d2a72bb0
           |-- fabric-biome-api-v1 13.0.25+be5d88beb0
           |-- fabric-block-api-v1 1.0.20+6dfe4c9bb0
           |-- fabric-block-view-api-v2 1.0.8+80f8cf51b0
           |-- fabric-blockrenderlayer-v1 1.1.50+80f8cf51b0
           |-- fabric-client-tags-api-v1 1.1.12+7f945d5bb0
           |-- fabric-command-api-v1 1.2.45+f71b366fb0
           |-- fabric-command-api-v2 2.2.24+80f8cf51b0
           |-- fabric-commands-v0 0.2.62+df3654b3b0
           |-- fabric-content-registries-v0 8.0.5+b82b2392b0
           |-- fabric-convention-tags-v1 2.0.4+7f945d5bb0
           |-- fabric-convention-tags-v2 2.1.0+70fd1b46b0
           |-- fabric-crash-report-info-v1 0.2.27+80f8cf51b0
           |-- fabric-data-attachment-api-v1 1.1.16+2a2c66b6b0
           |-- fabric-data-generation-api-v1 19.1.0+ad474493b0
           |-- fabric-dimensions-v1 2.1.68+94793913b0
           |-- fabric-entity-events-v1 1.6.8+e9d2a72bb0
           |-- fabric-events-interaction-v0 0.7.6+c5fc38b3b0
           |-- fabric-game-rule-api-v1 1.0.50+80f8cf51b0
           |-- fabric-item-api-v1 8.2.0+5bcea88ab0
           |-- fabric-item-group-api-v1 4.0.39+aae0949ab0
           |-- fabric-key-binding-api-v1 1.0.45+80f8cf51b0
           |-- fabric-keybindings-v0 0.2.43+df3654b3b0
           |-- fabric-lifecycle-events-v1 2.3.4+c5fc38b3b0
           |-- fabric-loot-api-v2 3.0.5+97f703dab0
           |-- fabric-message-api-v1 6.0.10+109a837cb0
           |-- fabric-model-loading-api-v1 1.0.12+80f8cf51b0
           |-- fabric-models-v0 0.4.11+9386d8a7b0
           |-- fabric-networking-api-v1 4.0.8+0dca0349b0
           |-- fabric-object-builder-api-v1 15.1.4+c5fc38b3b0
           |-- fabric-particles-v1 4.0.0+c5fc38b3b0
           |-- fabric-recipe-api-v1 5.0.3+c5fc38b3b0
           |-- fabric-registry-sync-v0 5.0.16+ad474493b0
           |-- fabric-renderer-api-v1 3.2.12+97f703dab0
           |-- fabric-renderer-indigo 1.5.12+80f8cf51b0
           |-- fabric-renderer-registries-v1 3.2.61+df3654b3b0
           |-- fabric-rendering-data-attachment-v1 0.3.46+73761d2eb0
           |-- fabric-rendering-fluids-v1 3.1.3+2c869dedb0
           |-- fabric-rendering-v0 1.1.64+df3654b3b0
           |-- fabric-rendering-v1 4.2.4+b21c00cbb0
           |-- fabric-resource-conditions-api-v1 4.1.0+83154f1bb0
           |-- fabric-resource-loader-v0 1.1.0+c0e5481fb0
           |-- fabric-screen-api-v1 2.0.21+7b70ea8ab0
           |-- fabric-screen-handler-api-v1 1.3.73+8c7b71c2b0
           |-- fabric-sound-api-v1 1.0.21+c5fc38b3b0
           |-- fabric-transfer-api-v1 5.1.6+c5fc38b3b0
           \-- fabric-transitive-access-wideners-v1 6.0.10+74e2f560b0
        - fabricloader 0.15.11
           \-- mixinextras 0.3.5
        - fallingtree 1.20.6.4
        - ferritecore 6.1.1
        - flan 1.20.5-1.10.2
           \-- rtree-3i-lite-fabric 0.3.0
        - forgeconfigapiport 20.6.0
           |-- com_electronwill_night-config_core 3.6.7
           \-- com_electronwill_night-config_toml 3.6.7
        - glasscarpet 1.2.0-1.20.5
        - glitchcore 1.1.0.6
           |-- com_electronwill_night-config_core 3.6.7
           |-- com_electronwill_night-config_toml 3.6.7
           \-- net_jodah_typetools 0.6.3
        - hopobettermineshaft 1.2.3
        - hopobetterruinedportal 1.4.1
        - hopobetterunderwaterruins 1.1.7
        - java 22
        - journeymap 5.9.31
           \-- journeymap-api-fabric 1.20.5-1.9-fabric-SNAPSHOT
        - krypton 0.2.7
           \-- com_velocitypowered_velocity-native 3.2.0-SNAPSHOT
        - lithium 0.12.3
        - lolmct 1.2.7
        - luckperms 5.4.128
           \-- fabric-permissions-api-v0 0.3.1
        - minecraft 1.20.6
        - modernfix 5.17.3+mc1.20.6
        - moreberries 1.5.10
        - mr_dungeons_andtaverns 3.2
        - mr_dynamic_torches 1-v2
        - mr_immortal_armadillo 1-v.1.0.1
        - mr_katters_structures 1.8
        - mr_nice_mobsremastered 2.1.5
        - mr_qraftyfied 7.6
        - mr_tidal_towns 1.3
        - netherportalspread 8.2
        - niftycarts 3.4.1+1.20.6
        - nohostilesaroundcampfire 6.0
        - notenoughanimations 1.7.3
        - pathunderfencegates 1.4.0+mc1.20.x
        - quad 1.2.1
        - realisticbees 3.8
        - replantingcrops 5.3
        - sereneseasons 9.4.0.4
           |-- com_electronwill_night-config_core 3.6.7
           |-- com_electronwill_night-config_toml 3.6.7
           \-- net_jodah_typetools 0.6.3
        - strayed_fates_forsaken 1.1.2.0
        - strayspawn 3.6
        - terrablender 3.5.0.3
           |-- com_electronwill_night-config_core 3.6.7
           \-- com_electronwill_night-config_toml 3.6.7
        - terralith 2.5.0
        - villagernames 7.4

**Comment by jmb05** [comment]
This is an incompatibility with pathunderfencegates, I'll look into it

**Comment by jmb05** [comment]
Turns out this issue is because pathunderfencegates is incompatible with Minecraft 1.20.6, and it also crashes when trying to make path blocks with shovel in hand. This means it has to reported there.
